# Generated by Django 2.2.10 on 2020-02-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='testing',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
